/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_GAria2 (void);
GtkWidget* create_preferences (void);
GtkWidget* create_aboutdialog (void);
GtkWidget* create_filechooserdialog (void);
GtkWidget* create_dialogNew (void);
