/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

#include "garia2.h"

GtkWidget *g_GAria2;
Preferences g_preference;

int
main (int argc, char *argv[])
{
	GtkWidget *filechooserdialog;

#ifdef ENABLE_NLS
	bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
	bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
	textdomain (GETTEXT_PACKAGE);
#endif

	gtk_set_locale ();
	gtk_init (&argc, &argv);

	add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

	load_settings(&g_preference);

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
	g_GAria2 = create_GAria2 ();
	init_tree(GTK_TREE_VIEW(lookup_widget(GTK_WIDGET(g_GAria2), "treeview")));
	gtk_widget_show (g_GAria2);

//  preferences = create_preferences ();
//  gtk_widget_show (preferences);
 // gtk_widget_show (aboutdialog);
//  filechooserdialog = create_filechooserdialog ();
//  gtk_widget_show (filechooserdialog);
//  dialogNew = create_dialogNew ();
//  gtk_widget_show (dialogNew);

  gtk_main ();
  return 0;
}

